# Generated by Django 4.2 on 2023-05-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'place', 'verbose_name_plural': 'places'},
        ),
        migrations.AlterModelTable(
            name='place',
            table='place',
        ),
    ]
